#!/usr/bin/env bash
#
# PreToolUse hook — refuse edits to generated files.
#
# CLAUDE.md asks Claude not to edit compiled CSS/JS. That is advisory; this is
# not. Editing assets/css/*.css instead of src/scss/*.scss produces work that
# the next `npm run build` silently destroys, which is a genuinely expensive
# mistake to debug.
#
# Contract (https://code.claude.com/docs/en/hooks):
#   stdin  : JSON with .tool_name and .tool_input.file_path
#   exit 0 : allow (fall through to normal permission handling)
#   exit 2 : block, and show stderr to Claude so it can correct course
#
set -uo pipefail

INPUT="$(cat)"

# jq is not guaranteed to be installed. Fall back to a narrow grep/sed
# extraction of the file_path field rather than failing the whole hook.
if command -v jq >/dev/null 2>&1; then
	FILE_PATH="$(printf '%s' "$INPUT" | jq -r '.tool_input.file_path // empty')"
else
	FILE_PATH="$(printf '%s' "$INPUT" \
		| tr ',' '\n' \
		| grep -m1 '"file_path"' \
		| sed -E 's/.*"file_path"[[:space:]]*:[[:space:]]*"(.*)".*/\1/')"
fi

# Native Windows sends C:\Users\...\main.css, and the fallback above leaves
# the JSON escaping in place (C:\\Users\\...). Normalize to forward slashes,
# or none of the */assets/css/* patterns below would ever match on Windows.
FILE_PATH="$(printf '%s' "$FILE_PATH" | sed -E 's#\\+#/#g')"

# Nothing to check (e.g. a tool call without a path) — let it through.
[[ -z "${FILE_PATH:-}" ]] && exit 0

block() {
	printf 'Refusing to edit a generated file: %s\n\n%s\n' "$FILE_PATH" "$1" >&2
	exit 2
}

case "$FILE_PATH" in
	*/assets/css/*.css|*/assets/css/*.css.map)
		block "Compiled by build/compile-scss.mjs and overwritten on the next build.
Edit the source instead: themes/*/src/scss/ — then run 'npm run scss'." ;;
	*/assets/js/*.js|*/assets/js/*.js.map)
		block "Bundled by build/bundle-js.mjs and overwritten on the next build.
Edit the source instead: themes/*/src/js/ — then run 'npm run js'." ;;
	*/node_modules/*)
		block "node_modules is managed by npm. Change package.json instead." ;;
	*/package-lock.json)
		block "Generated by npm. Run the appropriate npm command instead of editing it." ;;
	*/vendor/*)
		block "vendor/ is managed by Composer. Change composer.json instead." ;;
esac

exit 0
